### ISSUE TITLE
UI : Unable to vote for the game mode Freezetag using the ingame menu

### ISSUE THREAD

**Issue by 3aTmE** [PadWorld-Entertainment/worldofpadman#165]
### The issue :
When trying to vote for the Freezetag game mode using the ingame menu a vote for the Free for All Game Mode will be started instead.

![Screenshot 2022-06-04 220617](https://user-images.githubusercontent.com/84514074/172024066-3d0660e7-4e16-4240-8f40-b103b69a10f3.png)

### How to replicate : 
- Start a local game on any game mode than Freezetag
- call a vote for Freezetag
- The game should now vote for the wrong game mode (FFA) instead.

**Comment by mgerhardy** [comment]
should be fixed

**Comment by 3aTmE** [comment]
> should be fixed

Wow! That was fast!

Just tried it by myself. 
Unfortunately the issue still persists on my end. 
I've pulled the changes and build my executable but sadly its still not working proper. 

I've deleted also my `worldofpadman` folder in `AppData\Roaming` . 
Still no changes to the behaviour.

**Comment by 3aTmE** [comment]
Issue is now fixed 👍
